# Generated by Django 4.1.6 on 2023-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower_like_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updatedtimestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
