# Generated by Django 4.1.6 on 2023-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_updatedtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updatedtimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
