# Generated by Django 4.1.6 on 2023-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
